### PR TITLE
Fix check method

### PR DESCRIPTION
**Pull request by szepeviktor**
1. it returns a boolean
2. add strict comparison

### CODE REVIEW

**Comment by divine** [comment]
Thank you very much!

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
@divine WAIT! Should `check()` say the given username is on the list?
Then we don't need the `!`

**Comment by divine** [comment]
Ah, that's the reason why we need tests 😁.

No worries, going to fix it :)

Thanks!

**Pull request merged**
